# Generated by Django 4.1.3 on 2022-12-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_delete_curso_delete_entregable_delete_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
